### PR TITLE
Change the logger package to winston and remove the fireway

### PR DESCRIPTION
**Pull request by hrabizadeh-sa**

### CODE REVIEW

**Review by gvko — CHANGES_REQUESTED** [review]
I'm sorry, but why exactly should we be changing from `bunyan` to `winston` ?

**Comment by hrabizadeh-sa** [comment]
> I'm sorry, but why exactly should we be changing from `bunyan` to `winston` ?

Hi Gvko,
I've looked into your package, and when I attempted to deploy my project to production, I noticed that two of the dependency packages haven't been updated for the past three years. I had two options: either implement the code myself in my repository or fork your project and update the outdated packages. Considering that we're using Winston instead of Bunyan, which hasn't been updated and contains vulnerable packages, I thought it would be best to switch to Winston.

I'm willing to contribute to this project by adding more features and ensuring that the dependent packages are regularly updated, making them accessible for everyone to use.

By the way, I prefer not to directly update your package. I've already forked it, but I accidentally pushed my changes to your repository. you can ignore my PR and I'll push it to my repo.

**Comment by gvko** [comment]
> > I'm sorry, but why exactly should we be changing from `bunyan` to `winston` ?
> 
> Hi Gvko, I've looked into your package, and when I attempted to deploy my project to production, I noticed that two of the dependency packages haven't been updated for the past three years. I had two options: either implement the code myself in my repository or fork your project and update the outdated packages. Considering that we're using Winston instead of Bunyan, which hasn't been updated and contains vulnerable packages, I thought it would be best to switch to Winston.
> 
> I'm willing to contribute to this project by adding more features and ensuring that the dependent packages are regularly updated, making them accessible for everyone to use.
> 
> By the way, I prefer not to directly update your package. I've already forked it, but I accidentally pushed my changes to your repository. you can ignore my PR and I'll push it to my repo.

Fair enough. Let's merge your PR. Contributions are welcome. 🙌 
I haven't been using this package in a long time, that's why I haven't been maintaining it. Didn't know people actually use it. :)
You can start using this repo directly, instead of your own, if you want. And I'll help you maintain it.

**Comment by gvko** [comment]
hey @hrabizadeh-sa , I've published to npmjs the latest version (0.0.5) with your PR changes.

> I'm willing to contribute to this project by adding more features and ensuring that the dependent packages are regularly updated, making them accessible for everyone to use.

This ☝️ is welcome. Thanks for the contribution! 🙌

**Pull request merged**
